project_id = "lfqpuynqhcjuvoqgjhtt"

[functions.check-availability]
verify_jwt = false

[functions.create-booking]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.send-booking-confirmation]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = true
